// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnionInfrastructure;

#nullable disable

namespace OnionApi.Migrations.EFProductRepositoryMigrations
{
    [DbContext(typeof(EFProductRepository))]
    [Migration("20230515193114_productmig")]
    partial class productmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("OnionCore.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartId");

                    b.HasIndex("ProductId");

                    b.ToTable("Part");
                });

            modelBuilder.Entity("OnionCore.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OnionCore.Part", b =>
                {
                    b.HasOne("OnionCore.Product", null)
                        .WithMany("RequiredParts")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("OnionCore.Product", b =>
                {
                    b.Navigation("RequiredParts");
                });
#pragma warning restore 612, 618
        }
    }
}
